services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "mydb"]
      interval: 5s
      retries: 5
      start_period: 5s  
      timeout: 3s 


  express:
    build: .
    container_name: express-container
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: mydb
    working_dir: /app
    volumes:
      - .:/app
    command: ["npm", "start"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
